# This workflow runs on pushes to any branch
name: "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push some to master or production branch.

on:
  push:
    branches:
      - "**"

jobs:
  hello_world:
   runs-on: ubuntu-latest
   steps:
      - name: "Print Hello world"
        run: echo "Hello World"
      - name: "Print current date"
        run: date
      